from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import wfdb


LEADS_12 = ["I", "II", "III", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]


class PaperQRSUnavailable(RuntimeError):
    pass


@dataclass(frozen=True)
class PaperQRSExecutables:
    wqrs: Path
    eplimited: Path


def _resolve_exe(name: str, *, params: dict[str, Any], work_dir: Path) -> Path:
    param_key = f"{name}_exe"
    env_key = f"SQI_{name.upper()}_EXE"
    candidates: list[str | Path | None] = [
        params.get(param_key),
        os.environ.get(env_key),
        work_dir / "tools" / "bin" / f"{name}.exe",
        work_dir / "tools" / "bin" / name,
        shutil.which(name),
    ]
    for candidate in candidates:
        if not candidate:
            continue
        p = Path(str(candidate))
        if p.exists() and p.is_file():
            return p if p.is_absolute() else Path.cwd() / p
    raise PaperQRSUnavailable(
        f"Missing paper QRS executable '{name}'. Set {env_key}, pass {param_key}, "
        f"or place it under {work_dir / 'tools' / 'bin'}."
    )


def resolve_paper_qrs_executables(params: dict[str, Any], work_dir: Path) -> PaperQRSExecutables:
    return PaperQRSExecutables(
        wqrs=_resolve_exe("wqrs", params=params, work_dir=work_dir),
        eplimited=_resolve_exe("eplimited", params=params, work_dir=work_dir),
    )


def _safe_record_name(record_id: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]+", "_", str(record_id))
    return safe[:80] or "record"


def _write_temp_wfdb_record(
    tmp_dir: Path,
    record_id: str,
    sig12: np.ndarray,
    fs: int,
    leads: list[str],
) -> str:
    if leads != LEADS_12:
        raise ValueError(f"paper QRS expects 12-lead order {LEADS_12}, got {leads}")
    record_name = _safe_record_name(record_id)
    sig = np.asarray(sig12, dtype=np.float64)
    wfdb.wrsamp(
        record_name=record_name,
        fs=float(fs),
        units=["mV"] * sig.shape[1],
        sig_name=leads,
        p_signal=sig,
        fmt=["32"] * sig.shape[1],
        adc_gain=[200.0] * sig.shape[1],
        baseline=[0] * sig.shape[1],
        comments=["temporary record generated by src.sqi_pipeline.qrs.paper_detectors"],
        write_dir=str(tmp_dir),
    )
    return record_name


def _prepend_warmup(sig12: np.ndarray, warmup_samples: int) -> tuple[np.ndarray, int]:
    if warmup_samples <= 0:
        return sig12, 0
    if sig12.shape[0] == 0:
        raise ValueError("cannot prepend warmup to an empty signal")
    if warmup_samples <= sig12.shape[0]:
        prefix = sig12[:warmup_samples, :]
    else:
        reps = int(np.ceil(warmup_samples / sig12.shape[0]))
        prefix = np.tile(sig12, (reps, 1))[:warmup_samples, :]
    return np.concatenate([prefix, sig12], axis=0), int(prefix.shape[0])


def _run_command(exe: Path, args: list[str], cwd: Path) -> None:
    env = os.environ.copy()
    env["WFDB"] = str(cwd)
    env["PATH"] = str(exe.parent) + os.pathsep + env.get("PATH", "")
    proc = subprocess.run(
        [str(exe), *args],
        cwd=str(cwd),
        env=env,
        text=True,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        msg = (proc.stderr or proc.stdout or "").strip()
        if proc.returncode == 3221225781:
            msg = (
                "Windows failed to load a dependent DLL. "
                f"Prepended {exe.parent} to PATH before launch. {msg}"
            ).strip()
        raise RuntimeError(f"{exe.name} failed with code {proc.returncode}: {msg[:1000]}")


def _read_ann_samples(tmp_dir: Path, record_name: str, annotator: str) -> np.ndarray:
    ann_path = tmp_dir / f"{record_name}.{annotator}"
    if not ann_path.exists():
        raise RuntimeError(f"Expected annotation file was not created: {ann_path}")
    ann = wfdb.rdann(str(tmp_dir / record_name), annotator)
    samples = np.asarray(ann.sample, dtype=int)
    samples = samples[np.isfinite(samples)]
    samples = samples[(samples >= 0)]
    return np.unique(samples.astype(int))


def _remove_ann(tmp_dir: Path, record_name: str, annotator: str) -> None:
    p = tmp_dir / f"{record_name}.{annotator}"
    if p.exists():
        p.unlink()


def run_paper_qrs_12lead(
    *,
    record_id: str,
    sig12: np.ndarray,
    fs: int,
    leads: list[str],
    executables: PaperQRSExecutables,
    work_dir: Path,
    eplimited_warmup_sec: float = 8.0,
) -> tuple[list[np.ndarray], list[np.ndarray]]:
    """
    Run paper detectors on a 12-lead 125 Hz record.

    EP Limited/Hamilton initializes its QRS threshold over the first eight
    seconds. Challenge records are only 10 seconds, so the wrapper prepends a
    warmup copy for eplimited and then maps annotations back to the original
    record span. wqrs is run on the original record.

    Returns:
      rpeaks_1 = wqrs annotations per lead
      rpeaks_2 = eplimited annotations per lead
    """
    work_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="paper_qrs_", dir=str(work_dir)) as td:
        tmp_dir = Path(td)
        sig = np.asarray(sig12, dtype=np.float64)
        record_name = _write_temp_wfdb_record(tmp_dir, f"{record_id}_wqrs", sig, fs, leads)
        warmup_samples = int(round(float(eplimited_warmup_sec) * fs))
        sig_epl, epl_offset = _prepend_warmup(sig, warmup_samples)
        epl_record_name = _write_temp_wfdb_record(tmp_dir, f"{record_id}_epl", sig_epl, fs, leads)
        epl_end = epl_offset + sig.shape[0]

        wqrs_all: list[np.ndarray] = []
        epl_all: list[np.ndarray] = []
        for lead in leads:
            _remove_ann(tmp_dir, record_name, "wqrs")
            _run_command(executables.wqrs, ["-r", record_name, "-s", lead], cwd=tmp_dir)
            wqrs_all.append(_read_ann_samples(tmp_dir, record_name, "wqrs"))

            _remove_ann(tmp_dir, epl_record_name, "epl")
            _run_command(executables.eplimited, ["-r", epl_record_name, "-s", lead], cwd=tmp_dir)
            epl = _read_ann_samples(tmp_dir, epl_record_name, "epl")
            if epl_offset:
                epl = epl[(epl >= epl_offset) & (epl < epl_end)] - epl_offset
            else:
                epl = epl[epl < sig.shape[0]]
            epl_all.append(np.unique(epl.astype(int)))

    return wqrs_all, epl_all
